### ISSUE TITLE
饼图增加percentToFixed精度属性计算百分比异常

### ISSUE THREAD

**Issue by xiang20933** [DataV-Team/DataV-React#1]
## Bug report
pie新增percentToFixed:2，在特定数据下百分比计算错误

#### 出现Bug的组件？
Charts

#### 组件配置数据？
option: {
          color: ['#19aef2', '#4bdbc6', '#f87421'],
          title: {
            text: '本日***',
            style: {
              fill: 'white',
            },
            show: false
          },
          series: [
            {
              type: 'pie',
              data: [
                { name: 'test1', value: 20000 },
                { name: 'test2', value: 3000 },
              ],
              insideLabel: {
                show: true
              },
              percentToFixed: 2
            }
          ]
        }

#### 期望情况？
百分比显示正常
#### 实际情况？
![image](https://user-images.githubusercontent.com/50788862/71428002-cf4e9500-26f8-11ea-8593-716b777f9e58.png)

#### 其他相关信息

- DataV版本 1.0.7
- 浏览器版本 谷歌
- 其他

**Comment by yizhiyuyou** [comment]
@jiaming743  你看看，是不是chart的问题。

**Comment by jiaming743** [comment]
@yizhiyuyou @xiang20933 应该是的 正在排查

**Comment by jiaming743** [comment]
更新datav依赖**charts**至版本`@jiaminghi/charts@0.2.10`即可解决，参见该版本[release](https://github.com/DataV-Team/Charts/releases/tag/V0.2.10-alpha)
