### ISSUE TITLE
轮播表显示或者隐藏行号的时候，显示异常，拖动或者修改轮播表宽度可以恢复

### ISSUE THREAD

**Issue by XueMeijing** [DataV-Team/DataV-React#10]
## Bug report
轮播表显示或者隐藏行号的时候，显示异常，拖动或者修改轮播表宽度可以恢复
#### 出现Bug的组件？
轮播表
#### 期望情况？
显示或者隐藏行号的时候，按照columnWidth显示

#### 实际情况？
切换的时候显示异常
![image](https://user-images.githubusercontent.com/35559153/88273819-56a2cc00-cd0d-11ea-84b2-7013ae977b00.png)
![image](https://user-images.githubusercontent.com/35559153/88273836-615d6100-cd0d-11ea-89fa-4545dd6b9c6b.png)

#### 其他相关信息
大佬，我又来了，如果不是bug能请教下应该怎么做吗，现在在二次开发davinci数据大屏，需要把行号变成可配置的 可复现demo链接 https://github.com/XueMeijing/dataV-test.git
- DataV版本
- 浏览器版本
- 其他

**Comment by XueMeijing** [comment]
另外如果数据行数较少，而rowNum较大，hoverPause设置为true的时候，会报好多错误
![image](https://user-images.githubusercontent.com/35559153/88275624-45a78a00-cd10-11ea-8305-9b1e852da9f1.png)

**Comment by yizhiyuyou** [comment]
@XueMeijing  这里有两个问题。
1. 切换显示列时，列显示宽度异常
2. 悬浮异常
@jiaming743  第一个问题你需要看一下，在 Vue 版本可能也存在。第二个我改一下。

**Comment by yizhiyuyou** [comment]
@XueMeijing 1.2.4 版本已修复悬浮异常问题。
