### ISSUE TITLE
动态环图里翻牌器和名称的宽高可以加配置吗

### ISSUE THREAD

**Issue by XueMeijing** [DataV-Team/DataV-React#12]
## Feature request
宽度只有100，名称或者数据过长显示不全，我在CRender里找不到设置宽度的地方
![image](https://user-images.githubusercontent.com/35559153/88908522-8c573000-d28c-11ea-8d4e-31d8cbd4553f.png)

#### 这个特性解决了什么问题？
如果动态环图某项属性过长，显示不全

#### 这个特性的实现形式？
能否加个宽高配置

**Comment by XueMeijing** [comment]
![image](https://user-images.githubusercontent.com/35559153/89171180-5dee9300-d5b3-11ea-97d3-6990841d680a.png)
大佬，我写了配置样式，但是翻牌器的canvas超过七位还是显示不全，加了宽度只能拉伸

**Comment by yizhiyuyou** [comment]
@jiaming743

**Comment by XueMeijing** [comment]
> @jiaming743

名称的宽高可以自己加样式设置，但是canvas里的数字和百分比最多显示7位数，加了宽高只是拉伸，不过环图用来显示百分比比较多吧，超过七位数的情况还是比较少

**Comment by jiaming743** [comment]
@XueMeijing 下个大版本会考虑优化配置 暂时先用css控制吧

**Comment by XueMeijing** [comment]
> @XueMeijing 下个大版本会考虑优化配置 暂时先用css控制吧

吼的～
