### ISSUE TITLE
debounce

### ISSUE THREAD

**Issue by alphabetabc** [DataV-Team/DataV-React#15]
#### 新组件的类型？

* [ ] 边框
* [ ] 装饰
* [ ] 图表
* [x] 其他

#### 这个组件的功能描述 (边框及装饰类，请提供样图)？
@jiaminghi/data-view-react/src/util/index.js
在使用过程中，发现在组件销毁后，仍然调用setWH方法，导致报错；所以是否应该在debounce方法上提供一个cancel方法

**Comment by yizhiyuyou** [comment]
@alphabetabc  更新至 1.2.5 。
