### ISSUE TITLE
请教个问题技术问题~

### ISSUE THREAD

**Issue by ayo4code** [DataV-Team/DataV-React#16]
边框组件我看了下你是通过svg实现的，涉及到宽度改变时线宽跟着更改，装饰元素不变的逻辑是自己找到所有线手写的逻辑么？还是有什么工具可以自动生成？

**Comment by jiaming743** [comment]
SVG本来就都是我手写的，没有用什么工具

**Comment by ayo4code** [comment]
> SVG本来就都是我手写的，没有用什么工具

了解了 感谢
