### ISSUE TITLE
在BorderBox8中使用svg会自动absolute定位

### ISSUE THREAD

**Issue by sdutwsl** [DataV-Team/DataV-React#17]
## Bug report
在BorderBox8中使用svg会自动absolute定位
#### 出现Bug的组件
BorderBox8
#### 组件的less样式源码
```
.dv-border-box-8 {
  position: relative;
  width: 100%;
  height: 100%;

  svg {
    position: absolute;
    width: 100%;
    height: 100%;
    left: 0px;
    top: 0px;
  }

  .border-box-content {
    position: relative;
    width: 100%;
    height: 100%;
  }
}
```

#### 期望情况
svg不自动abosolute定位

#### 实际情况
svg被.dv-border-box-8 svg 选中了

#### 其他相关信息

- DataV版本：DataV-React最新版
- 浏览器版本：Chrome 86

**Comment by yizhiyuyou** [comment]
@sdutwsl  更新至 1.2.5.
