### ISSUE TITLE
期望react版-飞线组件可以出灵活配置

### ISSUE THREAD

**Issue by wuanyang** [DataV-Team/DataV-React#2]
真心给作者大大点个赞，组件炒鸡好用

**Comment by jiaming743** [comment]
哪方面的配置？

**Comment by wuanyang** [comment]
就是和飞线增强版（vue版）一样，增加点到点之间的飞线

**Comment by jiaming743** [comment]
有的，React版文档忘记同步更新了，组件名是`FlylineChartEnhanced`，配置项和Vue版一样，先参考Vue版文档吧，后续会更新React版文档

**Comment by wuanyang** [comment]
OK
