### ISSUE TITLE
可以加些折线图吗？加上折线图，基本上就够用了

### ISSUE THREAD

**Issue by zepc007** [DataV-Team/DataV-React#4]
## Component request
可以加些折线图吗？加上折线图，基本上就够用了
#### 新组件的类型？

* [ ] 边框
* [ ] 装饰
* [√ ] 图表
* [ ] 其他

**Comment by yizhiyuyou** [comment]
@jiaming743

**Comment by jiaming743** [comment]
@zepc007 指的是哪种折线图？

**Comment by zepc007** [comment]
> @zepc007 指的是哪种折线图？

基本的折线图就行，我看现在一个折线图都没😂

**Comment by yizhiyuyou** [comment]
@zepc007  内部使用了[(Charts)]( http://charts.jiaminghi.com/guide/). 有折线图，柱状图，饼状图，雷达图，仪表盘。
