### ISSUE TITLE
引入@jiaminghi/data-view-react报错，提示需要新增.d.ts文件 declare module @jiaminghi/data-view-react

### ISSUE THREAD

**Issue by wxmcool** [DataV-Team/DataV-React#6]
#### 实际情况？
尝试新增.d.ts文件并定义如下
declare module '@jiaminghi/data-view-react' {
  export const BorderBox1: any
  export const BorderBox2: any
}

使用import * as datav from '@jiaminghi/data-view-react'不再报错
  if(true){
    return <datav.Decoration1 />
  }
报错提示，Error:(11, 19) TS2694: Namespace '"@jiaminghi/data-view-react"' has no exported member 'BorderBox1'.
#### 其他相关信息

- DataV版本 1.2.1 
- 浏览器版本 chrome  83.0.4103.106
- 其他

**Comment by yizhiyuyou** [comment]
@wxmcool  因为现在组件库不是使用 TypeScript 写的。所以会有上面的这个问题。这一段时间，会使用 TypeScript 重构。
