### ISSUE TITLE
边框和装饰动态传高度和宽度，必须要重新刷新页面才能生效

### ISSUE THREAD

**Issue by wxmcool** [DataV-Team/DataV-React#7]
## Bug report
边框和装饰动态传高度和宽度，必须要重新刷新页面才能生效
#### 其他相关信息

- DataV版本 1.2.1
- 浏览器版本
- 其他

**Comment by yizhiyuyou** [comment]
@wxmcool 您好，可以给我一个复现例子。

**Comment by wxmcool** [comment]
不好意思，应该是我的组件bug问题，可以关闭此ISSUE了
